In [144]:
import numpy as np
import pandas as pd

# SERIES

In [145]:
arr = pd.Series(np.arange(1,5))
print(f'Array :\n{arr}')

Array :
0    1
1    2
2    3
3    4
dtype: int64

In [146]:
print(f'Array Values : {arr.values}\n')
print(f'Array Index : {arr.index}\n')
print(f'Array Data Type : {arr.dtype}\n')

Array Values : [1 2 3 4]

Array Index : RangeIndex(start=0, stop=4, step=1)

Array Data Type : int64

In [147]:
arr = pd.Series(['Thilak', 'Siva', 'Vignesh', 'Vishnu'])
print(f'Array : \n{arr}\n')
print('Value in 1st Index :',arr[1])

Array :
0     Thilak
1       Siva
2    Vignesh
3     Vishnu
dtype: str

Value in 1st Index : Siva

In [148]:
print(f'Iloc : {arr.iloc[1]}\n')

Iloc : Siva

## Slicing

In [149]:
print(f'loc : \n{arr.loc[1:3]}\n')
print(f'Iloc : \n{arr.iloc[1:3]}\n')

loc :
1       Siva
2    Vignesh
3     Vishnu
dtype: str

Iloc :
1       Siva
2    Vignesh
dtype: str

In [150]:
print(f'Iloc : \n{arr.iloc[0:3]}\n')

Iloc :
0     Thilak
1       Siva
2    Vignesh
dtype: str

## Indexing

In [151]:
arr = pd.Series([1,2,3,4,5], index=['A','B','C','D','E'])
print(f'Array : \n{arr}\n')
print(f'Indexing (B): {arr["B"]}\n')

Array :
A    1
B    2
C    3
D    4
E    5
dtype: int64

Indexing (B): 2

## Arithmetic Operations

In [152]:
print(f'Array Addition: \n{arr+5}\n')
print(f'Array Subtraction: \n{arr-5}\n')

Array Addition:
A     6
B     7
C     8
D     9
E    10
dtype: int64

Array Subtraction:
A   -4
B   -3
C   -2
D   -1
E    0
dtype: int64

## Statistical Operations

In [153]:
print(f'Sum : {arr.sum()}')
print(f'Min : {arr.min()}')
print(f'Max : {arr.max()}')
print(f'Max : {arr.max()}')
print(f'Mean : {arr.mean()}')
print(f'Median : {arr.median()}')
print(f'Standard Deviation : {arr.std()}')

Sum : 15
Min : 1
Max : 5
Max : 5
Mean : 3.0
Median : 3.0
Standard Deviation : 1.5811388300841898

## String Operations

In [154]:
name = pd.Series(['Thilak', 'Siva', 'Vignesh', 'Vishnu', 'Subash'])
print(f'Array: \n{name}\n')

Array:
0     Thilak
1       Siva
2    Vignesh
3     Vishnu
4     Subash
dtype: str

In [155]:
print(f'String Upper: \n{name.str.upper()}\n')
print(f'String Lower: \n{name.str.lower()}\n')
print(f'String Length: \n{name.str.len()}\n')

String Upper:
0     THILAK
1       SIVA
2    VIGNESH
3     VISHNU
4     SUBASH
dtype: str

String Lower:
0     thilak
1       siva
2    vignesh
3     vishnu
4     subash
dtype: str

String Length:
0    6
1    4
2    7
3    6
4    6
dtype: int64

In [156]:
arr = pd.Series({'Vishnu':23, 'thilak': 52, 'Vignesh': 33})
print(f'Array: \n{arr}\n')

Array:
Vishnu     23
thilak     52
Vignesh    33
dtype: int64

In [157]:
print(f'Value of Vishnu : {arr["Vishnu"]}')

Value of Vishnu : 23

In [158]:
arr1 = pd.Series([10,10,30], index=['A','B','B'])
print(f'Array 1: \n{arr1}\n')

arr2 = pd.Series([1,2,3], index=['B','C','D'])
print(f'Array 2: \n{arr2}\n')

# Addition
print(f'Array Addition - Index Based: \n{arr1+arr2}\n')

Array 1:
A    10
B    10
B    30
dtype: int64

Array 2:
B    1
C    2
D    3
dtype: int64

Array Addition - Index Based:
A     NaN
B    11.0
B    31.0
C     NaN
D     NaN
dtype: float64

In [159]:
print(f'Elements Count: {arr1.count()}')
print(f'Unique Elements: {arr1.unique()}')
print(f'Unique Elements Count: {arr1.nunique()}')

Elements Count: 3
Unique Elements: [10 30]
Unique Elements Count: 2

# DATA FRAME

In [160]:
data = pd.DataFrame({
    'name':['Vishnu', 'Vignesh', 'Thilak'],
    'mark': [34, 65, 99],
    'age':[12, 20, 25]
})
print(f'Data Frame :\n',data)

Data Frame :
       name  mark  age
0   Vishnu    34   12
1  Vignesh    65   20
2   Thilak    99   25

In [161]:
roll_no = pd.Series([11,12,49,53, 55])
name = pd.Series(['Vishnu', 'Vignesh', 'Thilak', 'Siva', 'Subash'])
age = pd.Series([21,22,24,23,19])
attendance = pd.Series([True, False, False, True, True])

print(f'Roll No: {roll_no}\n')
print(f'Name: {name}\n')
print(f'Age: {age}\n')
print(f'Attendance: {attendance}\n')

Roll No: 0    11
1    12
2    49
3    53
4    55
dtype: int64

Name: 0     Vishnu
1    Vignesh
2     Thilak
3       Siva
4     Subash
dtype: str

Age: 0    21
1    22
2    24
3    23
4    19
dtype: int64

Attendance: 0     True
1    False
2    False
3     True
4     True
dtype: bool

Create DataFrame with Series

In [162]:
df = pd.DataFrame({
    'roll_no': roll_no,
    'name':name,
    'age': age,
    'attendance': attendance
})
print(f'Data Frame:\n{df}')

Data Frame:
   roll_no     name  age  attendance
0       11   Vishnu   21        True
1       12  Vignesh   22       False
2       49   Thilak   24       False
3       53     Siva   23        True
4       55   Subash   19        True

Convert 2D List to DataFrame

In [163]:
data = [
    ['Vishnu', 22, 89],
    ['Vignesh', 21, 93],
    ['Siva', 20, 78],
]
print(f'Data : {data}\n')

df = pd.DataFrame(data)
print(f'DataFrame: \n{df}\n')

df = pd.DataFrame(data, columns=['Name','Age','Mark'])
print(f'DataFrame with Columns: \n{df}')

Data : [['Vishnu', 22, 89], ['Vignesh', 21, 93], ['Siva', 20, 78]]

DataFrame:
         0   1   2
0   Vishnu  22  89
1  Vignesh  21  93
2     Siva  20  78

DataFrame with Columns:
      Name  Age  Mark
0   Vishnu   22    89
1  Vignesh   21    93
2     Siva   20    78

Convert Dictionary to DataFrame

In [164]:
data = [
    {'Name': 'Vishnu', 'Age': 22, 'Mark': 89},
    {'Name': 'Vignesh', 'Age': 21, 'Mark': 93},
    {'Name': 'Siva', 'Age': 20, 'Mark': 78},
]

print(f'Data : {data}\n')

df = pd.DataFrame(data)
df

Data : [{'Name': 'Vishnu', 'Age': 22, 'Mark': 89}, {'Name': 'Vignesh', 'Age': 21, 'Mark': 93}, {'Name': 'Siva', 'Age': 20, 'Mark': 78}]

      Name  Age  Mark
0   Vishnu   22    89
1  Vignesh   21    93
2     Siva   20    78

Add New Row

In [165]:
df = pd.concat([df, pd.DataFrame([{'Name': 'Subash', 'Age': 29, 'Mark': 99}])], ignore_index=True)
print(f'DataFrame: \n{df}\n')

DataFrame:
      Name  Age  Mark
0   Vishnu   22    89
1  Vignesh   21    93
2     Siva   20    78
3   Subash   29    99

Add New Column

In [166]:
df['Grade'] = ['A', 'A+', 'B', 'C']
df

      Name  Age  Mark Grade
0   Vishnu   22    89     A
1  Vignesh   21    93    A+
2     Siva   20    78     B
3   Subash   29    99     C

Accessing Column

In [167]:
df[['Name','Age']]

      Name  Age
0   Vishnu   22
1  Vignesh   21
2     Siva   20
3   Subash   29

Accessing Row

In [168]:
df.iloc[1]

Name     Vignesh
Age           21
Mark          93
Grade         A+
Name: 1, dtype: object

In [169]:
print(f'Shape : {df.shape}')
print(f'No of Rows : {df.shape[0]}') 
print(f'No of Columns : {df.shape[1]}')

Shape : (4, 4)
No of Rows : 4
No of Columns : 4

In [170]:
print(f'Data Types : \n{df.dtypes}')

Data Types :
Name       str
Age      int64
Mark     int64
Grade      str
dtype: object

In [171]:
print(f'Data Frame Info : \n{df.info()}')

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Mark    4 non-null      int64
 3   Grade   4 non-null      str
dtypes: int64(2), str(2)
memory usage: 260.0 bytes
Data Frame Info :
None

In [172]:
print(f'Data Frame Describe : \n{df.describe()}')

Data Frame Describe :
             Age       Mark
count   4.000000   4.000000
mean   23.000000  89.750000
std     4.082483   8.845903
min    20.000000  78.000000
25%    20.750000  86.250000
50%    21.500000  91.000000
75%    23.750000  94.500000
max    29.000000  99.000000

In [173]:
df.loc[0,'Grade'] = 'C+'
df

      Name  Age  Mark Grade
0   Vishnu   22    89    C+
1  Vignesh   21    93    A+
2     Siva   20    78     B
3   Subash   29    99     C

## Delete in DataFrame

Delete a Row

In [174]:
df.drop(index=[0])

      Name  Age  Mark Grade
1  Vignesh   21    93    A+
2     Siva   20    78     B
3   Subash   29    99     C

Delete a Column

In [175]:
df.drop('Grade',axis=1,inplace=False)
df

      Name  Age  Mark Grade
0   Vishnu   22    89    C+
1  Vignesh   21    93    A+
2     Siva   20    78     B
3   Subash   29    99     C

In [176]:
df.drop('Grade',axis=1,inplace=True)
df

      Name  Age  Mark
0   Vishnu   22    89
1  Vignesh   21    93
2     Siva   20    78
3   Subash   29    99

## Sorting

In [178]:
df.sort_values('Age', inplace=True)
df

      Name  Age  Mark
2     Siva   20    78
1  Vignesh   21    93
0   Vishnu   22    89
3   Subash   29    99

In [179]:
df.sort_values('Age', inplace=True, ascending=False)
df

      Name  Age  Mark
3   Subash   29    99
0   Vishnu   22    89
1  Vignesh   21    93
2     Siva   20    78

## Statistical Function

In [ ]:
print(f'')

df['Mark'].max()

np.int64(99)