In [ ]:
import numpy as np
import pandas as pd

Read Excel file

In [ ]:
df = pd.read_excel('Dataset/InventryRecords.xlsx')
df.head()

,Product ID,Product Name,Opening \nStock,Purchase/\nStock in,Number of \nUnits Sold,Hand-In-\nStock,Cost Price \nPer Unit (USD),Cost Price\nTotal (USD)
0,P101,Laptop,50,20,10,60,1200,72000
1,P102,Monitor,40,15,5,50,500,25000
2,P103,Keyboard,60,25,15,70,50,3500
3,P104,Headphones,30,10,3,37,100,3700
4,P105,Smartphone,70,30,20,80,900,72000

Read JSON File

In [ ]:
df = pd.read_json('Dataset/titanicPassengers.json')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Check Null Values

In [ ]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

Count of Null Values

In [ ]:
df.isnull().count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            891
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          891
Embarked       891
dtype: int64

Find Null Values from a Column

In [ ]:
df['Age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [ ]:
df['Age'].isnull().count()

np.int64(891)

Replace Missing Values

In [ ]:
mean_age = df['Age'].mean()
df['Age'] = df['Age'].fillna(mean_age)
df['Age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

Fill Empty Cell with Mode

In [ ]:
df['Fare'].isnull().count()

np.int64(891)

In [ ]:
mean_fare = df['Fare'].mean()
df['Fare'] = df['Fare'].fillna(mean_fare)
df['Fare']

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

Delete a Row

In [ ]:
df.dropna(axis=1)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Change Index to PassengerId

In [ ]:
df = df.set_index('PassengerId')

Select Individual Record

In [ ]:
df.loc[1, [ 'Name', 'Age']]

Name    Braund, Mr. Owen Harris
Age                        22.0
Name: 1, dtype: object

Select Multiple Records

In [ ]:
df.loc[1:6, [ 'Name', 'Age']]

                                                          Name        Age
PassengerId
1                                      Braund, Mr. Owen Harris  22.000000
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  38.000000
3                                       Heikkinen, Miss. Laina  26.000000
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.000000
5                                     Allen, Mr. William Henry  35.000000
6                                             Moran, Mr. James  29.699118

Average Fare per Class

In [ ]:
df.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

Count Survivors by Gender

In [ ]:
df.groupby('Sex')['Survived'].count()

Sex
female    314
male      577
Name: Survived, dtype: int64

Multiple Aggregation

In [ ]:
df.groupby('Pclass').agg({
    'Age':['mean', 'min', 'max'],
    'Fare':['mean', 'sum']
})

              Age                   Fare
             mean   min   max       mean         sum
Pclass
1       37.048118  0.92  80.0  84.154687  18177.4125
2       29.866958  0.67  70.0  20.662183   3801.8417
3       26.403259  0.42  74.0  13.675550   6714.6951

Average Class Fare

In [ ]:
df['Avg_Class_Fare'] = df.groupby('Pclass')['Fare'].transform('mean')
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Avg_Class_Fare
PassengerId,,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,13.675550
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,84.154687
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,13.675550
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,84.154687
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,13.675550

In [ ]:
sample = pd.DataFrame({'Age':[20,25,None,35,40]})
sample

    Age
0  20.0
1  25.0
2   NaN
3  35.0
4  40.0

Estimate Missing Values using Interpolate

In [ ]:
sample['Age'] = sample['Age'].interpolate()
sample

    Age
0  20.0
1  25.0
2  30.0
3  35.0
4  40.0

## Students Dataset - Excel

In [ ]:
students = pd.read_excel('Dataset/studentsDataset.xlsx', sheet_name='students')
students.head()

   Student_ID       Name Department
0        1001  Student_1        CSE
1        1002  Student_2         IT
2        1003  Student_3        ECE
3        1004  Student_4        EEE
4        1005  Student_5       MECH

In [ ]:
marks = pd.read_excel('Dataset/studentsDataset.xlsx', sheet_name='marks')
marks.head()

   Student_ID  Maths  Python
0        1001     61      56
1        1002     62      57
2        1003     63      58
3        1004     64      59
4        1005     65      60

In [ ]:
contact = pd.read_excel('Dataset/studentsDataset.xlsx', sheet_name='contact')
contact.head()

   Student_ID                 Email
0        1001  student1@college.edu
1        1002  student2@college.edu
2        1003  student3@college.edu
3        1004  student4@college.edu
4        1005  student5@college.edu

## Inner Join

In [ ]:
inner_df = pd.merge(students, marks, on='Student_ID', how='inner')
inner_df.head()

   Student_ID       Name Department  Maths  Python
0        1001  Student_1        CSE     61      56
1        1002  Student_2         IT     62      57
2        1003  Student_3        ECE     63      58
3        1004  Student_4        EEE     64      59
4        1005  Student_5       MECH     65      60

## Left Join

In [ ]:
left_df = pd.merge(students, marks, on='Student_ID', how='left')
left_df.tail()

    Student_ID        Name Department  Maths  Python
45        1046  Student_46        CSE    NaN     NaN
46        1047  Student_47         IT    NaN     NaN
47        1048  Student_48        ECE    NaN     NaN
48        1049  Student_49        EEE    NaN     NaN
49        1050  Student_50       MECH    NaN     NaN

## Right Join

In [ ]:
right_df = pd.merge(students, marks, on='Student_ID', how='right')
right_df.head()

   Student_ID       Name Department  Maths  Python
0        1001  Student_1        CSE     61      56
1        1002  Student_2         IT     62      57
2        1003  Student_3        ECE     63      58
3        1004  Student_4        EEE     64      59
4        1005  Student_5       MECH     65      60

## Outer Join

In [ ]:
outer_df = pd.merge(students, marks, on='Student_ID', how='outer')
outer_df.head()

   Student_ID       Name Department  Maths  Python
0        1001  Student_1        CSE   61.0    56.0
1        1002  Student_2         IT   62.0    57.0
2        1003  Student_3        ECE   63.0    58.0
3        1004  Student_4        EEE   64.0    59.0
4        1005  Student_5       MECH   65.0    60.0

## Complete Merge

In [ ]:
students_complete = pd.merge(students, marks, on='Student_ID', how='left')
students_complete.head()

   Student_ID       Name Department  Maths  Python
0        1001  Student_1        CSE   61.0    56.0
1        1002  Student_2         IT   62.0    57.0
2        1003  Student_3        ECE   63.0    58.0
3        1004  Student_4        EEE   64.0    59.0
4        1005  Student_5       MECH   65.0    60.0

In [ ]:
students_complete = pd.merge(students_complete, contact, on='Student_ID', how='left')
students_complete.head()

   Student_ID       Name Department  Maths  Python                 Email
0        1001  Student_1        CSE   61.0    56.0  student1@college.edu
1        1002  Student_2         IT   62.0    57.0  student2@college.edu
2        1003  Student_3        ECE   63.0    58.0  student3@college.edu
3        1004  Student_4        EEE   64.0    59.0  student4@college.edu
4        1005  Student_5       MECH   65.0    60.0  student5@college.edu

---

## Concat - Row Wise

In [ ]:
part1 = students.iloc[:25]
part1.head()

   Student_ID       Name Department
0        1001  Student_1        CSE
1        1002  Student_2         IT
2        1003  Student_3        ECE
3        1004  Student_4        EEE
4        1005  Student_5       MECH

In [ ]:
part2 = students.iloc[25:]
part2.head()

    Student_ID        Name Department
25        1026  Student_26        CSE
26        1027  Student_27         IT
27        1028  Student_28        ECE
28        1029  Student_29        EEE
29        1030  Student_30       MECH

In [ ]:
combined_rows = pd.concat([part1, part2])
combined_rows.head()

   Student_ID       Name Department
0        1001  Student_1        CSE
1        1002  Student_2         IT
2        1003  Student_3        ECE
3        1004  Student_4        EEE
4        1005  Student_5       MECH

In [ ]:
combined_rows.shape

(50, 3)

## Concat - Column Wise

In [ ]:
student_basic = students[['Student_ID', 'Name']]
student_basic.head()

   Student_ID       Name
0        1001  Student_1
1        1002  Student_2
2        1003  Student_3
3        1004  Student_4
4        1005  Student_5

In [ ]:
student_marks = marks['Python']
student_marks.head()

0    56
1    57
2    58
3    59
4    60
Name: Python, dtype: int64

In [ ]:
combined_cols = pd.concat(
    [student_basic, student_marks], axis=1
)
combined_cols.head()

   Student_ID       Name  Python
0        1001  Student_1      56
1        1002  Student_2      57
2        1003  Student_3      58
3        1004  Student_4      59
4        1005  Student_5      60

## Joins

In [ ]:
students_index = students.set_index('Student_ID')
students_index.head()

                 Name Department
Student_ID
1001        Student_1        CSE
1002        Student_2         IT
1003        Student_3        ECE
1004        Student_4        EEE
1005        Student_5       MECH

In [ ]:
contact_index = contact.set_index('Student_ID')
contact_index.head()

                           Email
Student_ID
1001        student1@college.edu
1002        student2@college.edu
1003        student3@college.edu
1004        student4@college.edu
1005        student5@college.edu

In [ ]:
joined_df = students_index.join(contact_index)
joined_df.head()

                 Name Department                 Email
Student_ID
1001        Student_1        CSE  student1@college.edu
1002        Student_2         IT  student2@college.edu
1003        Student_3        ECE  student3@college.edu
1004        Student_4        EEE  student4@college.edu
1005        Student_5       MECH  student5@college.edu

## PIVOT TABLE

In [ ]:
df = pd.read_csv('Dataset/people.csv')
df.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon

In [ ]:
df.columns

Index(['Index', 'User Id', 'First Name', 'Last Name', 'Sex', 'Email', 'Phone',
       'Date of birth', 'Job Title'],
      dtype='str')

Create Age Column

In [ ]:
df['Date of birth'] = pd.to_datetime(df['Date of birth'])
df.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon

In [ ]:
today = pd.Timestamp.today()
df['Age'] = (
    (today - df['Date of birth']).dt.days // 365
)
df.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title,Age
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer,80
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist,116
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath,33
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher,8
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon,87

In [ ]:
pivot1 = pd.pivot_table(df, values='Age', index='Sex')
pivot1

              Age
Sex
Female  64.981132
Male    54.957447

Aggregate Function in pivot table

In [ ]:
pivot2 = pd.pivot_table(df, values='Age', index='Sex', aggfunc='count')
pivot2

        Age
Sex
Female   53
Male     47

Multiple Aggregation

In [ ]:
pivot3 = pd.pivot_table(df, values='Age', index='Sex', aggfunc=['count', 'mean', 'min', 'max'])
pivot3

       count       mean min  max
         Age        Age Age  Age
Sex
Female    53  64.981132   8  117
Male      47  54.957447   5  117

Pivot Table with Margins

In [ ]:
pivot4 = pd.pivot_table(df, values='Age', index='Sex', aggfunc='mean', margins=True)
pivot4

              Age
Sex
Female  64.981132
Male    54.957447
All     60.270000

Group by Job Title and Gender

In [ ]:
pivot5 = pd.pivot_table(df, values='Age', index='Job Title', columns='Sex', aggfunc='count')
pivot5.head()

Sex                               Female  Male
Job Title
Accountant, chartered management     1.0   1.0
Accounting technician                1.0   NaN
Advertising account executive        1.0   NaN
Agricultural consultant              NaN   1.0
Air broker                           1.0   NaN

Count People by Job and Gender, Fix NaN using fill_values

In [ ]:
pivot6 = pd.pivot_table(df, values='User Id', index='Job Title', columns='Sex', aggfunc='count', fill_value=0)
pivot6.head()

Sex                               Female  Male
Job Title
Accountant, chartered management       1     1
Accounting technician                  1     0
Advertising account executive          1     0
Agricultural consultant                0     1
Air broker                             1     0

# DATA CLEANING

In [ ]:
df = pd.read_excel('Dataset/dataCleaning.xlsx')
df.head()

   Student ID Student Name   Department   Age   Salary               Email
0         101      student1          IT  20.0  23075.0  student1@gmail.com
1         102      student2         ECE  18.0  35929.0  student2@gmail.com
2         103      STUDENT3         EEE  22.0  29718.0  student3@gmail.com
3         104      student4        MECH  20.0  21009.0  student4@gmail.com
4         105     Student5          CSE  19.0  47113.0  student5@gmail.com

In [ ]:
df.columns

Index(['Student ID', 'Student Name ', ' Department', 'Age', 'Salary', 'Email'], dtype='str')

Rename Columns

In [ ]:
df.rename(columns={'Student ID':'Student_ID','Student Name ':'Student_Name', ' Department':'Department'}, inplace=True)
df.columns

Index(['Student_ID', 'Student_Name', 'Department', 'Age', 'Salary', 'Email'], dtype='str')

Changing Data Types

In [ ]:
df.dtypes

Student_ID        int64
Student_Name        str
Department          str
Age             float64
Salary          float64
Email               str
dtype: object

In [ ]:
df['Student_ID'] = df['Student_ID'].astype(str)
df.dtypes

Student_ID          str
Student_Name        str
Department          str
Age             float64
Salary          float64
Email               str
dtype: object

In [ ]:
df['Age'] = df['Age'].fillna(0)
df['Age'] = df['Age'].astype(int)
df.dtypes

Student_ID          str
Student_Name        str
Department          str
Age               int64
Salary          float64
Email               str
dtype: object

Dedecting Duplicate Records

In [ ]:
duplicates = df.duplicated()
duplicates.head()

0    False
1    False
2    False
3    False
4    False
dtype: bool