In [35]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

Clean a messy HR Dataset: fix missing values, rename columns, group by department to compute average salary, merge with location table

Load Dataset

In [36]:
df = pd.read_csv('Dataset/employeeDataset.csv')
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [37]:
df.shape

(1020, 12)

In [38]:
df.dtypes

Employee_ID              str
First_Name               str
Last_Name                str
Age                  float64
Department_Region        str
Status                   str
Join_Date                str
Salary               float64
Email                    str
Phone                  int64
Performance_Score        str
Remote_Work             bool
dtype: object

Check and Rename Columns

In [39]:
df.columns

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Age', 'Department_Region',
       'Status', 'Join_Date', 'Salary', 'Email', 'Phone', 'Performance_Score',
       'Remote_Work'],
      dtype='str')

In [40]:
df.rename(columns={'Email':'Email_ID'}, inplace=True)
df.columns

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Age', 'Department_Region',
       'Status', 'Join_Date', 'Salary', 'Email_ID', 'Phone',
       'Performance_Score', 'Remote_Work'],
      dtype='str')

Change DataTypes

In [41]:
df['Age'] = df['Age'].astype('Int8')
df['Phone'] = df['Phone'].astype(str)

df[['Age', 'Phone']].head()

    Age        Phone
0    25  -1651623197
1  <NA>  -1898471390
2  <NA>  -5596363211
3    25  -3476490784
4    25  -1586734256

In [42]:
df.dtypes

Employee_ID              str
First_Name               str
Last_Name                str
Age                     Int8
Department_Region        str
Status                   str
Join_Date                str
Salary               float64
Email_ID                 str
Phone                    str
Performance_Score        str
Remote_Work             bool
dtype: object

In [43]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1015    False
1016    False
1017    False
1018    False
1019    False
Length: 1020, dtype: bool

In [44]:
df.drop_duplicates()
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email_ID,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,<NA>,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,<NA>,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

Handle Missing Values

In [45]:
# Phone
df['Phone'] = df['Phone'].str.slice(1)
df['Phone'].head()

0    1651623197
1    1898471390
2    5596363211
3    3476490784
4    1586734256
Name: Phone, dtype: str

In [46]:
mean_age = df['Age'].mean().astype(int)
df['Age'] = df['Age'].fillna(mean_age)
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email_ID,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,1651623197,Average,True
1,EMP1001,Bob,Brown,32,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,1898471390,Excellent,True
2,EMP1002,Alice,Jones,32,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,5596363211,Good,True
3,EMP1003,Eva,Davis,25,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,3476490784,Good,True
4,EMP1004,Frank,Williams,25,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,1586734256,Poor,False

Split Department and Region

In [47]:
df[['Department', 'Region']] = df['Department_Region'].str.split('-', n=1, expand=True)
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email_ID,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,32,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,32,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,1586734256,Poor,False,Cloud Tech,Florida

Drop Department_Region

In [48]:
df.drop(columns=['Department_Region'], inplace=True)
df.head()

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email_ID,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25,Active,4/2/2021,59767.65,bob.davis@example.com,1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,32,Active,7/10/2020,65304.66,bob.brown@example.com,1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,32,Pending,12/7/2023,88145.90,alice.jones@example.com,5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25,Inactive,11/27/2021,69450.99,eva.davis@example.com,3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25,Active,1/5/2022,109324.61,frank.williams@example.com,1586734256,Poor,False,Cloud Tech,Florida

Group by Department

In [49]:
dept_count = df.groupby('Department')['Employee_ID'].count()
dept_count.head()

Department
Admin         166
Cloud Tech    146
DevOps        189
Finance       170
HR            171
Name: Employee_ID, dtype: int64

In [51]:
avg_salary = df.groupby('Department')['Salary'].mean().map('{:.2f}'.format)
avg_salary

Department
Admin         85191.92
Cloud Tech    84923.04
DevOps        86016.02
Finance       82240.61
HR            85473.64
Sales         86896.68
Name: Salary, dtype: str